### ISSUE TITLE
Convert OGC document samples (batch 2)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#27]
* [x] ~~standard, subtype: implementation http://docs.opengeospatial.org/is/17-069r3/17-069r3.html~~ Merged in #36
* [x] ~~abstract-specification-topic http://docs.opengeospatial.org/as/15-104r5/15-104r5.html~~  Merged in #41
* [x] ~~best-practice (subtype: general) http://docs.opengeospatial.org/bp/16-114r3/16-114r3.html~~ Merged in #39
* [x] ~~discussion-paper http://docs.opengeospatial.org/dp/19-004.html~~ Merged in #40
* [x] ~~white-paper http://docs.opengeospatial.org/wp/16-131r2/16-131r2.html~~ Merged in #43
* [x] ~~other: Note, Primer, etc. https://portal.opengeospatial.org/files/15-120r5~~ Merged in #35
* [x] ~~release-notes https://portal.opengeospatial.org/files/18-016r1~~ (Merged in #32)

* change-request-supporting-document [could not find an example] -- NO SAMPLE YET
* community-practice [the first of this type is yet to be published] -- NO SAMPLE YET

**Comment by manuelfuenmayor** [comment]
Added `release-notes` doc sample in https://github.com/metanorma/mn-samples-ogc/pull/32

**Comment by manuelfuenmayor** [comment]
FYI, I opened a new bug related ticket here: https://github.com/metanorma/metanorma-ogc/issues/82

**Comment by manuelfuenmayor** [comment]
Added `15-120r5` in https://github.com/metanorma/mn-samples-ogc/pull/35

**Comment by anermina** [comment]
17-069r3 added in #36

**Comment by anermina** [comment]
16-114r3 added in #39

**Comment by anermina** [comment]
19-004 added in #40

**Comment by anermina** [comment]
15-104r5 added in #41

**Comment by manuelfuenmayor** [comment]
16-131r2 added in https://github.com/metanorma/mn-samples-ogc/pull/43

**Comment by ronaldtse** [comment]
All done here!
