### ISSUE TITLE
Convert OGC document samples (batch 1)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#9]
* [x] ~~community-standard (18-053r2 in #12) [http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html]~~ (merged)

* [x] ~~engineering-report (18-046 in #12) [http://docs.opengeospatial.org/per/18-046.html]~~ (merged)

* [x] ~~reference-model (08-062r7 in #12) [https://portal.opengeospatial.org/files/?artifact_id=47245]~~ (merged)

* [x] ~~user-guide (16-080 in #18) [https://docs.opengeospatial.org/guides/16-080.html]~~ (merged)

* [x] ~~policy (05-020r27 in #11) [http://docs.opengeospatial.org/pol/05-020r27/05-020r27.html]~~ (merged)

* [x] ~~profile (10-100r3 in #16) [http://portal.opengeospatial.org/files/?artifact_id=42729]~~ (merged)

* [x] ~~technical-corrigendum (14-065r2 in #26) [http://docs.opengeospatial.org/is/14-065/14-065.html]~~ (merged)

* [x] ~~standard-with-suite [most OGC standards fall under this category]~~ Moved to #27

* [x] ~~test-suite (00-027 in #25) [Catalog Service Interface 1.0 - Compliance Test](http://portal.opengeospatial.org/files/?artifact_id=945&version=1)~~ (merged)

**Comment by opoudjis** [comment]
https://metanorma.github.io/mn-ogc-documents/ is broken, @ronaldtse : these documents aren't publishing anywhere useful...

**Comment by ronaldtse** [comment]
The correct link is https://metanorma.github.io/mn-samples-ogc/ . Updating now.

**Comment by manuelfuenmayor** [comment]
Added policy sample (05-020r27) here: https://github.com/metanorma/mn-samples-ogc/pull/11

**Comment by ronaldtse** [comment]
@manuel489 @anermina could we add the remaining documents? Thanks.

**Comment by manuelfuenmayor** [comment]
Ok @ronaldtse , working on it.

**Comment by anermina** [comment]
@ronaldtse I'm also working on it. For now, additional two files are added ( #12 ).

**Comment by manuelfuenmayor** [comment]
Added `profile` sample in https://github.com/metanorma/mn-samples-ogc/pull/16

**Comment by ronaldtse** [comment]
ping @metanorma/editors could we complete the remaining 3 documents? Feel free to take them as you can. Thanks!

**Comment by anermina** [comment]
@ronaldtse , sure. 

Can you please add an example for standard-with-suite or confirm whether the following document can be used: http://docs.opengeospatial.org/is/10-140r2/10-140r2.html

Regarding the last document (test-suite), in order to open the link, I am required to log in to OGC portal system, to which I'm not registered. Is there some other option to see the file?

**Comment by ronaldtse** [comment]
@anermina the test-suite document is attached (00-027)
[00-027.zip](https://github.com/metanorma/mn-samples-ogc/files/4160147/00-027.zip)

Let me confirm with OGC on the standard-with-suite document.

**Comment by ronaldtse** [comment]
@anermina in any case the technical-corrigendum document is ready to go.

**Comment by anermina** [comment]
Thanks @ronaldtse ! @manuel489 is already working on technical-corrigendum and I'll take the test-suite.

**Comment by anermina** [comment]
test-suite is added in #25

**Comment by manuelfuenmayor** [comment]
technical-corrigendum added in https://github.com/metanorma/mn-samples-ogc/pull/26

**Comment by ronaldtse** [comment]
Thank you @anermina @manuel489 , this is all done and closing now!
